[theme]
primaryColor = "#D4A27C"
backgroundColor = "#FAFAF9"
secondaryBackgroundColor = "#F0EFED"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
