[theme]
primaryColor = "#D4A27C"
backgroundColor = "#FAFAF9"
secondaryBackgroundColor = "#F0EFED"
textColor = "#1A1A1A"
font = "sans serif"
base = "light"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
